	#model 20 = normal swords, axe, bow, crossbows
	#model 21 = other melee (also render regular swords and gunpowder)
	#model 22 = gunpowder (also render regular swords)
	#model 23 = LOD

	######################################
	#Musket mod compat
	nbt.1.Inventory=raw:iregex:.*(musket).*
	distanceFromPlayer.1=0-32
	models.1=22
	#LOD
	nbt.2.Inventory=raw:iregex:.*(musket).*
	models.2=23
	
	######################################
	#Custom named stuff and random weapons
	nbt.3.Inventory=raw:iregex:.*(Mace|Trident|Scythe|Staff\\s3|Staff\\s8|Staff\\s1|Staff\\s6|Staff\\s7|Staff\\s10|Staff\\s11|Staff\\s13|Deathsinger|Hadion|Niika|Thalleous|Chronos|GreatAxe|Xaria|Zeru|Double\\sHalberd|Halberd|Kaltaris|Mendoris|Nestoris|Sendaris|Tidesinger|Voltaris|Staff\\s2|Staff\\s4|Staff\\s5|Staff\\s9|Staff\\s12|Derp|Scythe|Staff\\s3|Staff\\s8).*
	distanceFromPlayer.3=0-32
	models.3=21	
	#LOD
	nbt.4.Inventory=raw:iregex:.*(Mace|Trident|Scythe|Staff\\s3|Staff\\s8|Staff\\s1|Staff\\s6|Staff\\s7|Staff\\s10|Staff\\s11|Staff\\s13|Deathsinger|Hadion|Niika|Thalleous|Chronos|GreatAxe|Xaria|Zeru|Double\\sHalberd|Halberd|Kaltaris|Mendoris|Nestoris|Sendaris|Tidesinger|Voltaris|Staff\\s2|Staff\\s4|Staff\\s5|Staff\\s9|Staff\\s12|Derp|Scythe|Staff\\s3|Staff\\s8).*
	models.4=23
	
	######################################
	#swords, axe, bow, crossbows
	distanceFromPlayer.5=0-21
	models.5=20
	#LOD
	models.6=23