#!/bin/zsh
# mms-hotswap-watch — recompile a mod on save and push the classes into the
# running MMS Dev client, with no game restart.
#
#   ./mms-hotswap-watch.sh mms-mod-compat-support
#
# How the pieces fit:
#   • Gradle runs with --continuous, so saving a .java file rebuilds it.
#   • The `hotswapClasses` task unpacks remapJar into build/hotswap/classes,
#     giving intermediary-named classes that match what the client loaded.
#     (The client runs the pack, not a dev env, so Mojmap classes would not
#     resolve -- this remap step is not optional.)
#   • HotswapAgent watches that dir via extraClasspath and redefines on change.
#
# What actually hotswaps:
#   ✓ method bodies in ordinary classes
#   ✓ adding/removing methods and fields  (needs JBR -- see mms-dev-setup.sh)
#   ~ mixin method bodies                 (via -Dmixin.hotSwap=true; flaky)
#   ✗ new @Inject / changed @At / new @Mixin class -- resolved at class load,
#     so these still need a full restart
#   ✗ registry and mod-init code -- it swaps, but it already ran
#
# The mod must already be running in the client. Deploy it once through the
# normal overlay path (./mms-deploy-test.sh with the slug in overlay.list)
# before hotswapping onto it.
set -e

slug="$1"
if [ -z "$slug" ]; then
    echo "usage: ./mms-hotswap-watch.sh <repo-slug>   e.g. mms-mod-compat-support" >&2
    exit 1
fi

repo="$HOME/Documents/GitHub/$slug"
[ -d "$repo" ] || { echo "!! no repo at $repo" >&2; exit 1; }
[ -f "$repo/gradlew" ] || { echo "!! $slug has no gradlew — not a Gradle mod repo." >&2; exit 1; }

classes="$repo/build/hotswap/classes"

if ! grep -q "hotswapClasses" "$repo/build.gradle"; then
    echo "!! $slug/build.gradle has no 'hotswapClasses' task." >&2
    echo "   Copy the task block from mms-mod-compat-support/build.gradle." >&2
    exit 1
fi

# HotswapAgent reads this at JVM start, but re-writing it costs nothing and
# keeps the watched dir in sync with whichever mod is under the microscope.
# Switching slugs therefore needs a client restart, not just a re-run.
# disabledPlugins is NOT optional. HotswapAgent enables all ~50 framework
# plugins by default; its Log4j2 plugin rewrites log4j's LoggerContext to call
# org.hotswap.agent.config.PluginManager, which Fabric's Knot classloader will
# not expose to game classes — the client dies with NoClassDefFoundError before
# Minecraft starts. Only the core redefinition plugins are left enabled.
cat > ~/.mms-dev/hotswap-agent.properties <<EOF
# generated by mms-hotswap-watch.sh — currently watching: $slug
autoHotswap=true
extraClasspath=$classes
watchResources=$classes
LOGGER=info
disabledPlugins=Hibernate,HibernateJakarta,Hibernate3,Hibernate3JPA,Spring,SpringBoot,Jersey1,Jersey2,Jetty,Tomcat,ZK,Logback,Log4j2,MyFaces,Mojarra,Omnifaces,ELResolver,WildFlyELResolver,OsgiEquinox,Owb,OwbJakarta,Proxy,WebObjects,Weld,WeldJakarta,JBossModules,ResteasyRegistry,Deltaspike,DeltaspikeJakarta,GlassFish,Weblogic,Vaadin,Wicket,CxfJAXRS,FreeMarker,Undertow,MyBatis,MyBatisPlus,IBatis,JacksonPlugin,Idea,Thymeleaf,Velocity,Sponge
EOF

echo "hotswap: watching $slug"
echo "         classes → $classes"
echo "         (if the client is already running and was watching a different"
echo "          mod, restart it once so the agent picks up the new path)"
echo

cd "$repo"
exec ./gradlew --continuous hotswapClasses
