name = "MMS Live"
author = "eli3"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8bc96411246369f23556a4dca9e8eacc22da7ffb1b156e80a8212c619fe314"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
