name = "MMS Live"
author = "eli3"
version = "2.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a488cf606cc50c752bdb93dbe173c39e55d71a6f32181caf4298b5c4e92f6b3c"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
