	#model 20 = Recruits normal swords, axe, bow, crossbows
	#model 21 = Recruits other melee (also render regular swords and gunpowder)
	#model 22 = Recruits gunpowder (also render regular swords)
	#model 23 = Recruits LOD
	
	#model 24 = Workers
	#model 25 = Workers LOD
	######################################
	#Worker mod
	######################################
	nbt.1.ProfessionName=exists:true
	distanceFromPlayer.1=0-32
	models.1=24
	
	nbt.2.ProfessionName=exists:true
	models.2=25
	
	######################################
	#Recruit mod
	######################################
	#Musket mod compat
	nbt.3.Items=raw:iregex:.*(musket).*
	nbt.3.LeftHanded=exists:true
	distanceFromPlayer.3=0-32
	models.3=22
	#LOD
	nbt.4.Items=raw:iregex:.*(musket).*
	nbt.4.LeftHanded=exists:true
	models.4=23
	
	######################################
	#Custom named stuff and random weapons
	nbt.5.Items=raw:iregex:.*(Mace|Trident|Scythe|Staff\\s3|Staff\\s8|Staff\\s1|Staff\\s6|Staff\\s7|Staff\\s10|Staff\\s11|Staff\\s13|Deathsinger|Hadion|Niika|Thalleous|Chronos|GreatAxe|Xaria|Zeru|Double\\sHalberd|Halberd|Kaltaris|Mendoris|Nestoris|Sendaris|Tidesinger|Voltaris|Staff\\s2|Staff\\s4|Staff\\s5|Staff\\s9|Staff\\s12|Derp|Scythe|Staff\\s3|Staff\\s8).*
	nbt.5.LeftHanded=exists:true
	distanceFromPlayer.5=0-32
	models.5=21	
	#LOD
	nbt.6.Items=raw:iregex:.*(Mace|Trident|Scythe|Staff\\s3|Staff\\s8|Staff\\s1|Staff\\s6|Staff\\s7|Staff\\s10|Staff\\s11|Staff\\s13|Deathsinger|Hadion|Niika|Thalleous|Chronos|GreatAxe|Xaria|Zeru|Double\\sHalberd|Halberd|Kaltaris|Mendoris|Nestoris|Sendaris|Tidesinger|Voltaris|Staff\\s2|Staff\\s4|Staff\\s5|Staff\\s9|Staff\\s12|Derp|Scythe|Staff\\s3|Staff\\s8).*
	nbt.6.LeftHanded=exists:true
	models.6=23
	
	######################################
	#swords, axe, bow, crossbows
	distanceFromPlayer.7=0-32
	nbt.7.LeftHanded=exists:true
	models.7=20
	#LOD
	nbt.8.LeftHanded=exists:true
	models.8=23
	
	######################################
	#Player model (Should be edited for a player pack that uses different models)
	######################################
	models.9=1