version = 1
enableSodiumMenu = true
dontCull = []
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 128
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "GAP"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
enderscape = true
rusticdelight = true
computerpc = true
mdm = true
farmersdelight = true
origins = true
rubies = true
modmetro = true
scorchful = true
storagedelight = true
computercraft = true
frostiful = true
friendsandfoes = true
biomeswevegone = true
alcocraftplus = true
eastersdelight = true
skniro_furniture = true
minecraft = true
furnish = true
displaydelight = true
