version = 1
enableSodiumMenu = true
dontCull = []
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 80
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
rusticdelight = true
enderscape = true
computerpc = true
mdm = true
farmersdelight = true
mutantmonsters = true
fishofthieves = true
origins = true
rubies = true
modmetro = true
scorchful = true
storagedelight = true
aerialhell = true
computercraft = true
uselessreptile = true
frostiful = true
friendsandfoes = true
biomeswevegone = true
alcocraftplus = true
eastersdelight = true
skniro_furniture = true
minecraft = true
furnish = true
displaydelight = true
