#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Wed Mar 18 19:11:46 EDT 2026
alwaysLogTamperWarnings=false
